version: "3.3"

services: 
  frontend: 
    container_name: turbo_tally.frontend 
    build: 
      context: ./frontend 
      dockerfile: Dockerfile 
    user: root 
    restart: always 
    ports: 
      - "30000:80" 
    privileged: true 
    env_file:
      - .env 
    command: bash start.sh 
    volumes: 
      - ./frontend:/home/turbo_tally.frontend 
    networks: 
      main:
        ipv4_address: 172.28.2.2


  backend: 
    container_name: turbo_tally.backend 
    build: 
      context: ./backend 
      dockerfile: Dockerfile
    tty: true
    user: root 
    restart: always
    ports: 
      - "30001:80"
    privileged: true 
    env_file: 
      - .env 
    command: bash start.sh
    volumes: 
      - ./backend:/home/turbo_tally.backend 
    networks: 
      main:
        ipv4_address: 172.28.2.3

  cache: 
    container_name: turbo_tally.cache
    image: redis:7.2.4-alpine 
    user: root
    restart: always
    ports: 
      - "30002:6379"
    privileged: true
    env_file: 
      - .env
    command: 
      redis-server --requirepass ${REDIS_PASSWORD} 
    volumes: 
      - cache:/data
      - ./backend/config/redis.conf:/usr/local/redis/redis.conf
    networks: 
      main:
        ipv4_address: 172.28.2.4

  database: 
    container_name: turbo_tally.database
    image: mongo:7.0.7-rc0-jammy
    user: root
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "30003:27017"
    command: 
      mongod
    volumes: 
      - database:/data/db
    networks: 
      main:
        ipv4_address: 172.28.2.5
      
volumes: 
  cache:
    driver: local
  database: 
    driver: local

networks: 
  main: 
    ipam:
        driver: default
        config:
          - subnet: 172.28.0.0/16